apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kros3
  name: kros3
  namespace: default
spec:
  selector:
    matchLabels:
      app: kros3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kros3
    spec:
      containers:
        - image: gcr.io/kwola-cloud/kros3:__REVISION_ID__
          imagePullPolicy: IfNotPresent
          name: kros3-sha256
          resources:
            requests:
              cpu: 50m
              memory: 75Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 15
